--T-SQL Fonksiyonlarda With Encryption Komutu


--EGER KI YAZMIS OLDUGUMUZ FONKSIYONLARIN KODLARINA 2. VE 3. SAHISLARIN ERISIMINI ENGELLEMEK ISTIYORSAK ''WITH ENCRYPTION'' KOMUTUNU KULLANMALIYIZ.
--BU ISLEMDEN SONRA FONKSIYONUN KODLARINI, KODU YAZAN KISI DAHIL KIMSE GOREMEZ. GERI DONUS YOKTUR. ANCAK FONKSIYONU OLUSTURAN KISININ KODUN YEDEGINI BULUNDURMASI GEREKMEKTEDIR. YA DA ''WITH ENCRYPTION'' OLMADAN KOD ''ALTER'' EDILEREK BASTAN YAZILMALIDIR.
--''AS'' KEYWORDUNDEN ONCE KULLANILMALIDIR.

CREATE FUNCTION ORNEKFONKSIYON()
RETURNS INT
WITH ENCRYPTION
AS
BEGIN
	RETURN 3
END	


CREATE FUNCTION ORNEKFONKSIYON2()
RETURNS TABLE
WITH ENCRYPTION
AS
	RETURN SELECT * FROM Personeller