--T-SQL Stored Procedures Tanımlama

--STORED PROCEDURE TANIMLAMA
CREATE PROC sp_ORNEK
(
	@ID INT --AKSI SOYLENMEDIGI TAKTIRDE BU PARAMETRENIN YAPISI INPUTTUR.
)
AS
SELECT * FROM Personeller WHERE PersonelID=@ID

