--T-SQL Geriye Değer Döndüren Stored Procedure

--OLUŞTURULMASI
CREATE PROC URUNGETIR
(
	@FIYAT MONEY
)
AS
SELECT * FROM Urunler WHERE BirimFiyati > @FIYAT
RETURN @@ROWCOUNT

--KULLANIMI
--ASAGIDAKI SEKILDE GERIYE DONULEN DEGERI ELDE ETMEKSIZIN KULLANILABILIR. SORUN OLMAZ.
EXEC URUNGETIR 40

DECLARE @SONUC INT
EXEC @SONUC = URUNGETIR 40
PRINT CAST(@SONUC AS NVARCHAR(MAX))+' ADET URUN BU ISLEMDEN ETKILENMISTIR'