--T-SQL Stored Procedures Örnek

USE Northwind
--####
--DISARIDAN ALDIGI ISIM, SOYISIM VE SEHIR BILGILERINI PERSONELLER TABLOSUNDA ILGILI KOLONA EKLEYEN STORED PROCEDURE'U YAZINIZ.
CREATE PROC sp_PERSONELEKLE
(
@AD NVARCHAR(MAX),
@SOYAD NVARCHAR(MAX),
@SEHIR NVARCHAR(MAX)
)
AS
INSERT Personeller(Adi,SoyAdi,Sehir) VALUES(@AD,@SOYAD,@SEHIR)

EXEC sp_PERSONELEKLE 'HASAN','YURDAKUL','ISTANBUL'
SELECT * FROM Personeller
