--T-SQL Stored Procedure - Parametrelere Varsayılan Değer Verme

USE Northwind

CREATE PROC sp_PERSONELEKLE
(
@AD NVARCHAR(50) = 'ISIM GIRILMEMIS',
@SOYAD NVARCHAR(50) = 'SOYISIM GIRILMEMIS',
@SEHIR NVARCHAR(50) = 'SEHIR GIRILMEMIS'
)
AS
INSERT Personeller(Adi,SoyAdi,Sehir) VALUES(@AD,@SOYAD,@SEHIR)


--BURADA DEFAULT DEGERLER DEVREYE GIRMEMEKTEDIR.
EXEC sp_PERSONELEKLE 'HASAN','YURDAKUL','ISTANBUL'


--ASAGIDAKI SORGUDA DEFAULT DEGERLER DEVREYE GIRECEKTIR.
EXEC sp_PERSONELEKLE

--ASAGIDAKI SORGUDA ISIM OLARAK HASAN DEGERINI ALACAKTIR ANCAK DIGER PARAMETRELER DEFAULT DEGERLERINI ALACAKTIR.
EXEC sp_PERSONELEKLE 'HASAN'