--T-SQL Triggerlar Giriş
USE Northwind

--#################
--DML TRIGGER
--BIR TABLODA INSERT, UPDATE VE DELETE ISLEMLERI GERCEKLESTIRILDIGINDE DEVREYE GIREN YAPILARDIR. BU ISLEMLER SONUCUNDA VEYA SURECINDE DEVREYE GIRERLER.	


--#################
--DDL TRIGGER
--CREATE, ALTER VE DROP ISLEMLERI SONUCUNDA VEYA SURECINDE DEVREYE GIRECEK TRIGGERLARA DENIR.