--T-SQL DML Triggerlar - Inserted ve Deleted Tabloları

--####################
--DML TRIGGERLAR

--## INSERTED TABLE
--EGER BIR TABLODA INSERT ISLEMI YAPILIYORSA ARKA PLANDA ISLEMLER ILK ONCE RAM'DE OLUSTURULAN ''INSERTED'' ISIMLI BIR TABLO UZERINDE YAPILIR. EGER ISLEMDE BIR PROBLEM YOK ISE INSERTED TABLOSUNDAKI VERILER, FIZIKSEL TABLOYA ISLENIR. ISLEM BITTIGINDE RAM'DE TUTULAN INSERTED TABLOSU SILINIR.

--## DELETED TABLE
--EGER BIR TABLODA DELETE ISLEMI YAPILIYORSA ARKA PLANDA ISLEMLER ILK ONCE RAM'DE OLUSTURULAN ''DELETED'' ISIMLI BIR TABLO UZERINDE YAPILIR. EGER ISLEMDE BIR PROBLEM YOK ISE DELETED TABLOSUNDAKI VERILER, FIZIKSEL TABLODAN DA SILINIR. ISLEM BITTIGINDE RAM'DE TUTULAN DELETED TABLOSU SILINIR.

--EGER BIR TABLODA UPDATE ISLEMI YAPILIYORSA, RAM'DE UPDATED ISIMLI BIR TABLO OLUSMAZ!!
--SQL SERVERDA UPDATE MANTIGI ONCE SILME(DELETE), SONRA EKLEME(INSERT) OLARAK CALISIR!!
--UPDATE ISLEMI SIRASINDA HEM INSERTED HEM DE DELETED TABLOLARI OLUSUR. VE ISLEMLER BU TABLOLAR UZERINDEN GERCEKLESTILIR.

--UPDATE YAPARKEN GUNCELLENEN KAYDIN ORJINALI DELETED TABLOSUNDA, GUNCELLENDIKTEN SONRAKI HALI ISE INSERTED TABLOSUNDA BULUNMAKTADIR.

--DELETED VE INSERTED TABLOLARI, ILGILI SORGU SONUCU OLUSTUKLARI ICIN O SORGUNUN KULLANDIGI KOLONLARA DA SAHIP OLUR. BOYLECE DELETED VE INSERTED TABLOLARINDAN SORGU YAPMAK MUMKUNDUR.

