--T-SQL Trigger Tanımlama
USE Northwind
--PROTOTIP 


--CREATE TRIGGER [TRIGGER_ADI]
--ON [ISLEM_YAPILACAK_TABLO_ADI]
--AFTER/FOR DELETE/UPDATE/INSERT
--AS
--KODLAR

--DIKKAT
--TANIMLANAN TRIGGERLARA, ILGILI TABLONUN ALTINDA BULUNAN TRIGGERS SEKMESINDEN ERISEBILIRIZ.

CREATE TRIGGER ORNEKTRIGGER
ON Personeller
AFTER INSERT
AS
SELECT * FROM Personeller

INSERT Personeller(Adi,	SoyAdi) VALUES('HASAN','YURDAKUL')

--ORNEK
--TEDARIKCILER TABLOSUNDAN BIR VERI SILINDIGINDE TUM URUNLERIN FIYATLARI OTOMATIK OLARAK 10 ARTSIN
CREATE TRIGGER FIYATARTIR
ON Tedarikciler
AFTER DELETE 
AS
UPDATE Urunler SET BirimFiyati = BirimFiyati + 10
SELECT * FROM Urunler

DELETE FROM Tedarikciler WHERE TedarikciID = 30



--ORNEK
--TEDARIKCILER TABLOSUNDA BIR VERI GUNCELLENDIGINDE, KATEGORILER TABLOSUNDA ''MEYVE KOKTEYLI'' ADINDA BIR KATEGORI OLUSSUN.
CREATE TRIGGER KOKTEYL_EKLE
ON Tedarikciler
AFTER UPDATE
AS
INSERT Kategoriler(KategoriAdi) VALUES('MEYVE KOKTEYLI')

UPDATE Tedarikciler SET MusteriAdi = 'HASAN' WHERE TedarikciID = 1
SELECT * FROM Kategoriler



--ORNEK
--PERSONELLER TABLOSUNDAN BIR KAYIT SILINDIGINDE, SILINEN KAYDIN ADI, SOYADI, KIM TARAFINDAN VE HANGI TARIHTE SILINDIGI BASKA BIR TABLOYA KAYIT EDILSIN.

CREATE TABLE LOGGER
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	RAPOR NVARCHAR(MAX)
)

CREATE TRIGGER tg_SILMEKAYDEDEN
ON Personeller
AFTER DELETE
AS
DECLARE @AD NVARCHAR(MAX), @SOYAD NVARCHAR(MAX)
SELECT @AD=Adi, @SOYAD=SoyAdi FROM DELETED
INSERT LOGGER VALUES ('ADI VE SOYADI' + @AD + ' ' + @SOYAD + ' OLAN PERSONEL ' + SUSER_SNAME() + ' TARAFINDAN ' + CAST(GETDATE() AS NVARCHAR(MAX)) + ' TARIHINDE SILINMISTIR.')

DELETE FROM Personeller WHERE PersonelID = 5

SELECT * FROM LOGGER



--ORNEK
--PERSONELLER TABLOSUNDA UPDATE ISLEMI GERCEKLESTIGI ANDA DEVREYE GIREN VE BIR LOG TABLOSUNA ''ADI ... OLAN PERSONEL ... YENI ADIYLA DEGISTIRILEREK, ... KULLANICISI TARAFINDAN ... TARIHINDE GUNCELLENDI.'' YAZDIRAN BIR TRIGGER'I YAZDIRALIM.

CREATE TABLE PERSONELLOG
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	RAPOR NVARCHAR(MAX)
)
CREATE TRIGGER tg_PERSONELLOGER
ON Personeller
AFTER UPDATE
AS
DECLARE @ESKIAD NVARCHAR(MAX), @ESKISOYAD NVARCHAR(MAX)
SELECT @ESKIAD=Adi, @ESKISOYAD=SoyAdi FROM DELETED
DECLARE @YENIAD NVARCHAR(MAX), @YENISOYAD NVARCHAR(MAX)
SELECT @YENIAD=Adi, @YENISOYAD=SoyAdi FROM INSERTED

INSERT PERSONELLOG VALUES ('ADI ' + @ESKIAD + ' ' + @ESKISOYAD + ' OLAN PERSONEL, ' + @YENIAD + ' ' + @YENISOYAD + ' YENI ADI ILE DEGISTIRILEREK ' + SUSER_SNAME() + ' TARAFINDAN ' + CAST(GETDATE() AS NVARCHAR(MAX)) + ' TARIHINDE GUNCELLENMISTIR.')

UPDATE Personeller SET Adi = 'HASAN' WHERE PersonelID = 1