--T-SQL DDL Triggerlar


--CREATE, ALTER VE DROP ISLEMLERI SONUCUNDA VEYA SURECINDE DEVREYE GIRECEK OLAN TRIGGERLARA DENIR.

CREATE TRIGGER DEMO
ON DATABASE
FOR DROP_TABLE, ALTER_TABLE, CREATE_FUNCTION, CREATE_PROCEDURE, DROP_PROCEDURE VS. VS. VS
AS
PRINT 'BU ISLEM GERCEKLESTIRILEMEZ.'
ROLLBACK


DROP TABLE LOGGER

