--T-SQL @@Identity, Scope_Identity ve Ident_Current Komutları


--@@IDENTITY
--ACILMIS OLAN BAGLANTIDA(CONNECTION), TABLO VEYA SORGUNUN CALISTIGI SCOPE'A BAKMAKSIZIN SON URETILEN IDENTITY DEGERINI VERMEKTEDIR.
--!!! DIKKAT !!!
--TRIGGER KULLANILAN YERLERDE ONGORULEMEZ SONUCLAR ALINMASI IHTIMALI OLDUGUNDAN KULLANILMASI TAVSIYE EDILMEZ.

INSERT Personeller(Adi,SoyAdi) VALUES('HASAN','YURDAKUL')
SELECT @@IDENTITY

--SCOPE_IDENTITY
--ACILMIS OLAN BAGLANTIDA(CONNECTION) VE SORGUNUN CALISTIGI SCOPE'DA SON URETILEN IDENTITY DEGERINI DONDURUR.
--!!! DIKKAT !!!
--TRIGGER KULLANILAN SORGULARDA @@IDENTITY YERINE BU FONKSIYONUN KULLANILMASI TAVSIYE EDILIR.

INSERT Personeller(Adi,SoyAdi) VALUES('HASAN','YURDAKUL')
SELECT SCOPE_IDENTITY()

--IDENT_CURRENT('TABLO_ADI')
--BAGLANTI VE SORGUNUN CALISTIRILDIGI SCOPE'A BAKMAKSIZIN PARAMETRE OLARAK VERILEN TABLODA URETILEN SONUNCU IDENTITY DEGERINI DONDURUR.

