--T-SQL Default Values İle Sadece Identity Kolonuna Veri Eklemek

--EGER KI VERITABANINDA GOREVI SADECE DIGER TABLOLAR TARAFINDAN REFERANS ALINACAGI ID'LERI URETECEK VE BARINDIRAKCAK OLAN BIR TABLOYA IHTIYAC VARSA KULLANILIR.

CREATE DATABASE ORNEKVERITABANI

CREATE TABLE ORNEKTABLO
(
	ID INT PRIMARY KEY IDENTITY,
	KOLON1 NVARCHAR(MAX),
	KOLON2 NVARCHAR(MAX)
)

USE ORNEKVERITABANI

INSERT ORNEKTABLO
DEFAULT VALUES