--T-SQL ROW_NUMBER Fonksiyonu

--PROTOTIPI
--ROW_NUMBER VE OVER BERABER KULLANILIR.
--SELECT ROW_NUMBER() OVER(ORDER BY KOLON_ADI) INDEXER, * FROM TABLO
USE Northwind

SELECT * FROM Personeller
SELECT ROW_NUMBER() OVER(ORDER BY PersonelID) INDEXER, * FROM Personeller
SELECT ROW_NUMBER() OVER(ORDER BY Adi) INDEXER, * FROM Personeller