--T-SQL ROW_NUMBER Fonksiyonu - Partition By Komutu İle Gruplama


USE Northwind

--SELECT ROW_NUMBER() OVER(PARTITION BY KOLON1 ORDER BY KOLON2) INDEXER, * FROM TABLO
--PARTION BY DENILEN KOLONA GORE BIR GRUPLAMA GERCEKLESTIRDIKTEN SONRA, ORDER BY KOLONUNA GORE INDEX ATAMASI GERCEKLESTIRIR.

SELECT ROW_NUMBER() OVER(PARTITION BY MusteriID ORDER BY OdemeTarihi) INDEXER ,* FROM Satislar