--T-SQL ANSI_NULLS Komutu


--SET ANSI_NULLS [ ON | OFF ]

--ANSI_NULLS KOMUTU, WHERE SARTLARINDA KONTROL EDILEN ESITLIK VEYA ESITSIZLIKLERDE NULL DEGERLERIN DIKKATE ALINIP ALINMAYACAGINI BELIRLEMEMIZI SAGLAYAN BIR OZELLIKTIR.

SET ANSI_NULLS OFF
SELECT * FROM Personeller WHERE Bolge = NULL
SET ANSI_NULLS ON