--SQL Server 2016 Dynamic Data Masking Uygulama

--PROTOTIP
--CREATE TABLE [TABLO_ADI]
--(
--	[KOLON_ADI] [KOLON_TIPI] MASKED WITH (FUNCTION = 'DEFAULT()')
--)
USE Northwind

CREATE TABLE OGRENCILER
(
	OGRENCIID INT PRIMARY KEY IDENTITY,
	ADI NVARCHAR(10) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	SOYADI NVARCHAR(10) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	MEMLEKETI NVARCHAR(10) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	TCNO INT MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	SUBE NVARCHAR(1) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	EMAIL NVARCHAR(MAX) MASKED WITH (FUNCTION = 'EMAIL()') NULL,
	HAKKINDA NVARCHAR(MAX) MASKED WITH (FUNCTION = 'PARTIAL(3, "H", 2)') NULL,
	DOGUMTARIHI DATETIME MASKED WITH (FUNCTION = 'DEFAULT()') NULL
)


INSERT OGRENCILER VALUES('HASAN','YURDAKUL','SIVAS','123123123','A','HSN@HSNYRDKL.COM','LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM','1998-08-15')
INSERT OGRENCILER VALUES('TAHA','YURDAKUL','SIVAS','123123123','A','HSN@HSNYRDKL.COM','BENIM ADIM TAHA YURDAKUL. MERHABA','1998-08-15')


SELECT * FROM OGRENCILER


CREATE USER YETKILIUSER WITHOUT LOGIN -- YETKILI USER ISMINDE BIR KULLANICI OLUSTURULUYOR.
GO
GRANT SELECT ON OGRENCILER TO YETKILIUSER -- YETKILIUSER KULLANICISINA OGRENCILER TABLOSUNDA SELECT ISLEMI YAPABILMESI ICIN YETKI VERILIYOR.


EXECUTE AS USER = 'YETKILIUSER'
SELECT * FROM OGRENCILER
REVERT --ESKI KULLANICIMIZA GERI DONMEMIZI SAGLAR