--SQL Server 2016 Dynamic Data Masking - Alter İle Kolunun Maske Formatını Güncelleme


ALTER TABLE OGRENCILER
ADD EKKOLON NVARCHAR(MAX) MASKED WITH (FUNCTION = 'PARTIAL(3,"XXXXX",0)')

ALTER TABLE OGRENCILER
ALTER COLUMN EKKOLON ADD MASKED WITH (FUNCTION = 'PARTIAL(5,"XX",2)')

EXECUTE AS USER = 'YETKILIUSER'
SELECT * FROM OGRENCILER
REVERT