--SQL Server 2016 Dynamic Data Masking Özelliğini Kullanıcıya Özel Pasifleştirme


GRANT UNMASK TO YETKILIUSER --MASKELEME ISLEMINI YETKILI USER ICIN PASIFLESTIRIR
REVOKE UNMASK TO YETKILIUSER  --MASKELEME ISLEMINI YETKILIUSER ICIN AKTIFLESTIRIR
EXECUTE AS USER = 'YETKILIUSER'
SELECT * FROM OGRENCILER
REVERT