--SQL Server 2016 Temporal Tables Çalışma Mantığı

--BIR VERININ ZAMANSAL TAKIBI

--VERI ILK KAYDEDILDIGINDE (INSERT)
--VERI ILK GUNCELLENDIGINDE (UPDATE)
--VERININ SONRAKI GUNCELLESTIRMELERINDE (UPDATE)