--SQL Server 2016 Temporal Tables Özelliğini Kullanırken Nelere Dikkat Etmeliyiz?

--TEMPORAL TABLES ILE RAPORLAMA VE TAKIP MEKANIZMASI OLUSTURACAGIMIZ TABLOLARDA PRIMARY KEY TANIMLANMIS BIR KOLON OLMASI GEREKMEKTEDIR. BU SEKILDE YASAM DONGUSUNDE HANGI VERININ DEGISIME UGRADIGINI BU PRIMARY KEY ILE TAKIP EDEBILECEGIZ.
--TAKIBI SAGLAYACAGIMIZ VE KAYDINI TUTACAGIMIZ TABLOMUZUN ICERISINDE BIR BASLANGIC (STARTDATE) VE BITIS (ENDDATE) NITELIGINDE IKI ADET ''DATETIME2'' TIPINDEN KOLONLARIN BULUNMASI GEREKMEKTEDIR.
--LINKED SERVER UZERINDE TEMPORAL TABLES KULLANILMAMAKTADIR.
--HISTORY TABLOMUZDA CONSTRAINT YAPILARININ HICBIRINI UYGULAYAMAYIZ.
--EGER BIR TABLODA TEMPORAL TABLES AKTIFSE O TABLODA TRUNCATE ISLEMI GERCEKLESTIREMEYIZ.
--HISTORY TABLOSUNDA DIREKT OLARAK DML ISLEMLERI GERCEKLESTIREMIYORUZ.
--TEMPORAL TABLES OZELLIGININ BULUNDUGU BIR TABLODA COMPUTED COLUMN (HESAPLANMIS KOLON) TANIMLAYAMAYIZ.