--SQL Server 2016 Veritabanındaki Temporal Tabloları Listelemek


SELECT 
NAME, OBJECT_ID, TEMPORAL_TYPE_DESC, HISTORY_TABLE_ID, OBJECT_NAME(HISTORY_TABLE_ID) 
AS [HISTORY_TABLOSU_ADI]
FROM SYS.TABLES WHERE OBJECT_NAME(HISTORY_TABLE_ID) IS NOT NULL


--YA DA


SELECT 
NAME, OBJECT_ID, TEMPORAL_TYPE_DESC, HISTORY_TABLE_ID, OBJECT_NAME(HISTORY_TABLE_ID) 
AS [HISTORY_TABLOSU_ADI]
FROM SYS.TABLES WHERE TEMPORAL_TYPE_DESC = 'SYSTEM_VERSIONED_TEMPORAL_TABLE'