--SQL Server 2016 Temporal Tables'i Pasifize Etme
--TEMPORAL TABLOLARDA TRUNCATE VE DROP ISLEMLERI UYGULANAMAZ. BU NEDENLE BU ISLEMLERI YAPMAK ISTIYORSAK ILK OLARAK TEMPORAL OZELLIGINI DEVRE DISI BIRAKMAMIZ GEREKIR. ARDINDAN TRUNCATE VE DROP ISLEMINI YAPABILIRIZ.

--TABLONUN TEMPORAL OZELLIGI DEVRE DISI KALDIGINDA ICINDEKI HISTORY TABLOSU, TABLONUN DISINA CIKARILIR.

ALTER TABLE dbo.DERSKAYITLARI 
SET(SYSTEM_VERSIONING = OFF)

TRUNCATE TABLE DERSKAYITLARI
DROP TABLE DERSKAYITLARI