USE Northwind



--GROUP BY KOMUTU
--GROUP BY İŞLEMİ GERÇEK KOLON İLE İLGİLİ İŞLEMLER YAPACAĞIMIZ YERLERDE KULLANILIR.
--AGGREGATE FONKSİYONUN ÇIKTILARININ BULUNACAĞI KOLONDA İŞLEM YAPACAĞIMIZ ZAMAN HAVING KOMUTUNU KULLANIRIZ.
SELECT KategoriID FROM Urunler
SELECT KategoriID,count(*) FROM Urunler GROUP BY KategoriID --KATEGORIID'LERİN COUNT'INI KATEGORI ID'YE GORE GRUPLAR
SELECT KategoriID,count(*) FROM Urunler WHERE(KategoriID<5) GROUP BY KategoriID --KATEGORIID'NIN 5'TEN KUCUK OLDUGU YERLERI KATEGORIID'YE GORE GRUPLAR
SELECT KategoriID,SUM(BirimFiyati) FROM URUNLER GROUP BY KategoriID --KATEGORIID'YE GORE BIRIM FIYATLARI TOPLAR VE KATEGORIID'YE GORE GRUPLANDIRIR
