USE Northwind

SELECT * FROM Urunler

--HAVING KOMUTU
--BURADA DA AGGREGATE FONKSİYONA GÖRE FİLTRELEME YAPABİLİRİZ.
SELECT KategoriID, Count(*) FROM Urunler Group By KategoriID Having Count(*)>7

--AYNI ŞEKİLDE BURADA DA WHERE KOMUTU KULLANABİLİRİZ.
--AŞAĞIDAKİ SORGUDA HEM KOLON, HEM DE AGG. FONKSİYON ÜZERİNE FİLTRELEME YAPTIK.
SELECT KategoriID, Count(*) FROM Urunler WHERE KategoriID>2 Group By KategoriID Having Count(*)>7
