USE Northwind

--INNER JOIN AYNI TABLOYU ILISKISEL OLARAK BIRLESTIRME
--PERSONELLERIN BAGLI OLARAK CALISTIGI KISILERI LISTELEYEN SORGU (PERSONELLER,PERSONELLER)
SELECT P1.Adi, P1.Unvan, P2.Adi Yönetici, P2.Unvan FROM Personeller P1 INNER JOIN Personeller P2 ON P1.BagliCalistigiKisi=P2.PersonelID