USE Northwind

--INNER JOIN'DE GROUP BY ISLEMI YAPMAK


--HANGI PERSONEL(ADI SOYADI ILE BIRLIKTE), TOPLAM KAÇ ADET SATIS YAPMIS? SATIS ADEDI 100'DEN FAZLA OLANLAR VE PERSONEL ADININ BAS HARFI M OLAN KAYITLARI GETIREN SORGU (PERSONELLER, SATISLAR)
SELECT P.Adi +' '+P.SoyAdi,COUNT(S.SatisID) FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID WHERE P.Adi LIKE 'M%' GROUP BY P.Adi +' '+P.SoyAdi HAVING COUNT(S.SatisID)>100

--SEAFOOD KATEGORISINDEKI URUNLERIN SAYISI (URUNLER, KATEGORILER)
SELECT K.KategoriAdi,COUNT(U.UrunAdi) FROM Urunler U INNER JOIN Kategoriler K ON U.KategoriID=K.KategoriID WHERE K.KategoriAdi='SEAFOOD' GROUP BY KategoriAdi

--HANGI PERSONEL TOPLAM KAÇ ADET SATIS YAPMIS?(PERSONELLER, SATISLAR)
SELECT * FROM Personeller,Satislar
SELECT P.PersonelID, COUNT(S.PersonelID) FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID GROUP BY P.PersonelID
SELECT P.Adi, COUNT(S.PersonelID) [Satış Adeti] FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID GROUP BY P.Adi


--EN ÇOK SATIŞ YAPAN PERSONEL KIM(PERSONELLER, SATISLAR)
SELECT TOP 1 P.Adi, COUNT(S.PersonelID) [Satış Adeti] FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID GROUP BY P.Adi ORDER BY [Satış Adeti] DESC

--ADINDA "A" HARFI OLAN PERSONELLERDEN, SATISID'SI 10500'DEN BUYUK OLAN SATISLARIN TOPLAM TUTARINI(MIKTAR*BIRIMFIYAT) VE BU SATISLARIN HANGI TARIHTE GERCEKLESTIGINI LISTELEYEN SORGU (PERSONELLER, SATISLAR,SATISDETAYLARI)
SELECT SUM(SD.BirimFiyati*SD.Miktar), S.SatisTarihi FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID INNER JOIN [Satis Detaylari] SD ON S.SatisID=SD.SatisID WHERE S.SatisID>10500 AND P.Adi LIKE '%A%' GROUP BY S.SatisTarihi