--OUTER JOIN 
--INNER JOIN'DE EŞLEŞEN KAYITLAR GETİRİLİYORDU
--OUTER JOIN'DE ISE ESLESMEYEN KAYITLAR DA GETİRİLİR.

--LEFT OUTER JOIN
--JOIN IFADESININ SOLUNDAKI TABLODAN OLAN TUM KAYITLARI GETIRIR. SAGINDAKI TABLODAN ESLESENLERI YANYANA, EŞLEŞMEYENLERİ NULL OLARAK YAZDIRIR.
--KULLANIRKEN ""LEFT OUTER JOIN"" YA DA ""LEFT JOIN"" OLARAK KULLANILABILIR

--RIGHT OUTER JOIN
--JOIN IFADESININ SAGINDAKI TABLODA OLAN TUM KAYITLARI GETIRIR. SOLUNDAKI TABLODAN ESLESENLERI YANYANA, ESLESMEYENLERI NULL OLARAK YAZDIRIR.
--KULLANIRKEN ""RIGHT OUTER JOIN"" YA DA ""RIGHT JOIN"" OLARAK KULLANILABILIR

--FULL OUTER JOIN
--JOININ IKI TARAFINDAKI TABLOLARDAN, EŞLEŞEN VEYA EŞLEŞMEYEN TÜM VERİLERİ GETİRİR.
--KULLANIRKEN ""FULL OUTER JOIN"" YA DA ""JOIN"" OLARAK KULLANILABILIR
