USE Northwind

--CROSS JOIN
--KARTEZYEN ÇARPIM OLARAK İKİ TABLOYU BİRLEŞTİRİR

SELECT COUNT(*) FROM Personeller
SELECT COUNT(*) FROM Bolge

SELECT P.Adi,B.BolgeID FROM Personeller P CROSS JOIN BOLGE B