USE Northwind
--DML (DATA MANIPULATION LANGUAGE)

--SELECT, INSERT, UPDATE, DELETE
--INSERT 2

--INSERT KOMUTU KULLANARAK SELECT SORGUSU ILE ELDE EDILEN VERILERI ""VAR OLAN"" FARKLI BIR TABLOYA KAYIT ETME
--SELECT SORGUSUNDA DONEN KOLON SAYISI ILE INSERT ISLEMI YAPILACAK TABLONUN KOLON SAYISI AYNI OLMALIDIR.
--INSERT OrnekPersoneller SELECT Adi,SoyAdi FROM Personeller
SELECT * FROM Personeller
--SELECT SORGUSU SONUCUNDA GELEN VERILERI FARKLI BIR TABLO OLUSTURARAK KAYDETME
--BURADA TABLO OLUSTURULURKEN PRIMARY VE FOREIGN KEYLER KAYIT EDILEMEZLER
SELECT Adi,SoyAdi,Ulke INTO #tmpPersoneller FROM Personeller



