	USE Northwind
	GO
	SELECT Adi,SoyAdi,Ulke INTO #tmpPersoneller FROM Personeller

	--DML (DATA MANIPULATION LANGUAGE)

	--SELECT, INSERT, UPDATE, DELETE

--UPDATE
--UPDATE [TABLOADI] SET [KOLONADI] = DEGER
--WHERE KOMUTU YAZMAZSAK ILGILI KOLONDAKI TUM SATIRLARI GUNCELLER
UPDATE #tmpPersoneller SET Adi ='MEHMET' WHERE Adi='NANCY'

--UPDATE SORGUSUNDA JOIN YAPILARI KULLANARAK BIRDEN FAZLA TABLODA GUNCELLEME YAPMAK
UPDATE Urunler SET UrunAdi=K.KategoriAdi FROM Urunler U INNER JOIN Kategoriler K ON U.KategoriID=K.KategoriID

--UPDATE SORGUSUNDA SUBQUERY ILE GUNCELLEME YAPMAK
UPDATE Urunler SET UrunAdi=(SELECT * FROM Personeller WHERE PersonelID=3)

--UPDATE SORGUSUNDA TOP KOMUTU ILE GUNCELLEME YAPMAK
UPDATE TOP(30) Urunler SET UrunAdi='X'

