USE Northwind
GO

--DML (DATA MANIPULATION LANGUAGE)

--SELECT, INSERT, UPDATE, DELETE

--DELETE
--DELETE FROM [TABLOADI]
DELETE FROM Urunler

--DELETE SORGUSUNA WHERE SARTI YAZMAK
DELETE FROM Urunler WHERE KategoriID<3

--DIKKAT EDILMESI GEREKENLER!!
--DELETE SORGUSUYLA TABLO ICERISINDEKI TUM VERIYI SILMEK IDENTITY KOLONUNU SIFIRLAMAYACAKTIR. SILME ISLEMINDEN SONRA ILK EKLENEN VERIDE IDENTITY KALDIGI YERDEN DEVAM EDECEKTIR. IDENTIY KOLONUNU DA SIFIRLAMAK ICIN TRUNCATE FONKSIYONU KULLANILMAKTADIR.