USE Northwind
GO

SELECT Adi,SoyAdi FROM Personeller
SELECT MusteriAdi,MusteriUnvani FROM Musteriler


--UNION | UNION ALL KOMUTLARI
--UNION 
--BIRDEN FAZLA SELECT SORGUSU KOMUTUNUN SONUCLARINI ALT ALTA GOSTERMEMIZI SAGLAR
SELECT Adi,SoyAdi FROM Personeller
UNION
SELECT MusteriAdi,MusteriUnvani FROM Musteriler

--IKIDEN FAZLA SORGUNUN UNION ILE BIRLESTIRILMESI DURUMU
SELECT Adi,SoyAdi FROM Personeller
UNION
SELECT MusteriAdi,MusteriUnvani FROM Musteriler
UNION
SELECT SevkAdi,SevkAdresi FROM Satislar

--JOINLER YANYANA, UNIONLAR ALT ALTA TABLOLARI BIRLESTIRIR.	JOINLERDE BELIRLI(ILISKISEL) BİR KOLON UZERINDEN BIRLESTIRME YAPILIRKEN, UNIONDA BOYLE BIR DURUM YOKTUR.

--DIKKAT EDILMESI GEREKEN KONULAR !!!!!
--UNION SORGUSUNUN SONUCUNDA OLUSAN TABLONUN KOLON ISIMLERI, EN USTTEKI SORGUNUN KOLON ISIMLERINDEN OLUSUR.
--USTTEKI SORGUDAN KAC KOLON CEKILMISSE ALTTAKI SORGUDAN DA O KADAR KOLON CEKILMEK ZORUNDADIR.
--USTTEKI SORGUDAN CEKILEN KOLONLARIN TIPLERIYLE, ALTTAKI SORGUDAN CEKILEN KOLONLARIN TIPLERI UYUMLU OLMALIDIR.
--UNION TEKRARLI KAYITLARI GETIRMEZ.

--UNIONDA KULLANILAN TABLOLARA KOLON EKLENEBILIR. DIKKAT ETMEMIZ GEREKEN NOKTA, YUKARIDAKI KURALLAR CERCEVESINDE ASAGIYA DA YUKARIYA DA AYNI SAYIDA KOLONLARIN EKLENMESI GEREKTIGIDIR.
SELECT Adi,SoyAdi, 'PERSONEL' TITLE FROM PERSONELLER --3 KOLON OLDU
UNION
SELECT MusteriAdi,MusteriUnvani,'MÜŞTERİ' FROM Musteriler --3 KOLON OLDU
ORDER BY TITLE	