USE Northwind
GO

--UNION | UNION ALL KOMUTLARI
--UNION ALL
--UNION TEKRARLI KAYITLARI GETİRMEZ DEMİŞTİK. TEKRARLI KAYITLARI GETIRMEK ICIN UNION ALL KOMUTUNU KULLANIRIZ.
-- AŞAĞIDAKI SORGU UNION ILE YAPILDIGINDA 190 KAYIT GETIRIR.
SELECT Adi,SoyAdi FROM Personeller
UNION 
SELECT MusteriAdi,MusteriUnvani FROM Musteriler
UNION 
SELECT SevkAdi,SevkAdresi FROM Satislar

--ANCAK UNION ALL KOMUTU KULLANILARAK SORGULANDIGINDA TEKRAR EDEN VERILERI DE GETIRECEGINDEN DOLAYI 930 KAYIT GETIRIR.
SELECT Adi,SoyAdi FROM Personeller
UNION ALL
SELECT MusteriAdi,MusteriUnvani FROM Musteriler
UNION ALL
SELECT SevkAdi,SevkAdresi FROM Satislar