USE Northwind
GO 

--WITH ROLLUP KOMUTU
--GROUP BY ILE GRUPLANMIS VERI KUMESINDE ARA TOPLAM ALINMASINI SAGLAR. WITH ROLLUP ILE YAPILAN SORGUDAKI NULL SATIRLAR ARA TOPLAMIN BELIRTILDIGI SATIRLARDIR.
SELECT SatisID,UrunID,SUM(Miktar) FROM [Satis Detaylari] GROUP BY SatisID,UrunID
SELECT SatisID,UrunID,SUM(Miktar) FROM [Satis Detaylari] GROUP BY SatisID,UrunID WITH ROLLUP

--HAVING SARTI ILE BERABER ROLL UP
SELECT SatisID,UrunID,SUM(Miktar) FROM [Satis Detaylari] GROUP BY SatisID,UrunID WITH ROLLUP HAVING SUM(Miktar)>100 