USE Northwind
GO

--WIHT CUBE 
--GROUP BY ISLEMI ILE GRUPLANDIRILMIS VERI KUMESINDE TEKER TEKER TOPLAM ALINMASINI SAGLAR

SELECT SatisID,UrunID,SUM(Miktar) FROM [Satis Detaylari] GROUP BY SatisID,UrunID WITH CUBE


--HAVING SARTI ILE BERABER WITH CUBE
SELECT SatisID,UrunID,SUM(Miktar) FROM [Satis Detaylari] GROUP BY SatisID,UrunID WITH CUBE HAVING SUM(Miktar)>100 