USE Northwind
GO
--T-SQL With Ties Komutu
--TOP SORGULAMASI YAPILIRKEN KULLANILMAKTADIR. ORDER BY KOLONU DA VERİLMEK ZORUNDADIR YOKSA SORGU CALISMAZ.
--AMACI== ORNEGIN "TOP 6" SORGUSU YAPTIK VE 7. VE 8. SORGULAR DA 6. SORGU ILE AYNI DEGERE SAHIP.
--BU DURUMDA 7. VE 8. SORGULAR DA CIKTIDA ELDE EDILECEKTIR.
SELECT * FROM [Satis Detaylari]

SELECT TOP 6 * FROM [Satis Detaylari]

--
SELECT TOP 6 WITH TIES * FROM [Satis Detaylari] ORDER BY SatisID
	


