USE Northwind
GO

--T-SQL With Yapısı

WITH PERSONELSATIS1(id,adi,soyadi,satisid)
AS
(
SELECT P.PersonelID,Adi,SoyAdi,SatisID FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID
)
SELECT * FROM PERSONELSATIS1

--YUKARIDAKI SORGUDAN ELDE EDILEN PERSONELSATIS TABLOSU DATABASE'E KAYDOLMAZ ANCAK ANLIK OLARAK ISLEMDE KULLANILABILIR. ORNEK:

WITH PERSONELSATIS2(id,adi,soyadi,satisid)
AS
(
SELECT P.PersonelID,Adi,SoyAdi,SatisID FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID
)
SELECT * FROM PERSONELSATIS2 PS2 INNER JOIN [Satis Detaylari] SD ON PS2.satisid=SD.SatisID