USE Northwind
GO 

--T-SQL SUBQUERY(IC ICE SORGULAR)
--BIR SORGUNUN CIKTISI, BASKA BIR SORGUNUN GIRDISI OLABILIR.
--AŞAĞIDAKİ SORGU NORMAL BIR SORGUDUR.
SELECT * FROM Personeller P INNER JOIN Satislar S ON P.PersonelID=S.PersonelID WHERE Adi='NANCY'

--SUBQUERY SORGUSUNDA ARANAN YERE PARANTEZ ICINDE, TABLO GETIREN BIR QUERY YAZILMALIDIR.
SELECT SatisID,SatisTarihi FROM Satislar WHERE PersonelID =(SELECT PersonelID FROM Personeller WHERE Adi='NANCY')