--T-SQL Truncate Table Komutu
USE Northwind
GO

DELETE FROM PERSX

TRUNCATE TABLE PERSX


--ICINDE VERI BULUNAN VE IDENTITY ICEREN BIR TABLO ''DELETE FROM'' KOMUTU ILE SILINDIKTEN SONRA IDENTITY KOLONU ''0''A DONMEZ YANI BASTAN BASLAMAZ.
--BU DURUMDA IDENTITY KOLONUNU BASTAN BASLATMAK ICIN ''TRUNCATE TABLE'' KOMUTUNU KULLANIRIZ.