--T-SQL @@Identity Komutu
USE Northwind
GO

--ILGILI VERI TABANI ICERISINDE YAPILAN EN SON ''INSERT'' ISLEMI OLAN SATIRIN IDENTITY'SINI VEREN KOMUTTUR.

INSERT Kategoriler(KategoriAdi,Tanimi) VALUES ('X','X KATEGORISI')

SELECT @@IDENTITY

INSERT Personeller(Adi,SoyAdi) VALUES ('Ela','Elif')	
