--T-SQL @@Rowcount Komutu

USE Northwind
GO

--YAPILAN ISLEM SONUCUNDA KAC ADET ELEMANIN ETKILENDIGINI BULMAYA YARAR.

DELETE FROM Personeller WHERE Adi='NANCY'
SELECT @@ROWCOUNT

SELECT * FROM Personeller
SELECT @@ROWCOUNT

INSERT Personeller(Adi,SoyAdi) VALUES ('HASAN','YURDAKUL'),('TAHA','YURDAKUL'),('MUSTAFA KEMAL','ATATURK')
SELECT @@ROWCOUNT
