--T-SQL IsNull Fonksiyonu İle Null Değer Kontrolü
USE Northwind

SELECT MusteriAdi,Bolge FROM Musteriler


SELECT MusteriAdi,
CASE
	WHEN Bolge   IS NULL THEN 'BOLGE BILINMIYOR' 
	ELSE Bolge 
END	[BOLGEISMI]
FROM Musteriler

--IS NULL
--COALESCE'DEN FARKLI OLARAK ISNULL'DA BOLGE KOLONU VERISI VARCHAR(15) ISE 15 KARAKTERLIK VERI GIRISI YAPABILIRIZ ANCAK COALESCE'DE BOYLE BIR SINIRLAMA YOKTUR.
SELECT MusteriAdi, ISNULL(Bolge,'BOLGE BILINMIYOR') FROM Musteriler