--T-SQL NullIf Fonksiyonu İle Null Değer Kontrolü

USE Northwind

--FONKSIYONA VERILEN KOLON, IKINCI PARAMETRE OLARAK VERILEN DEGERE ESIT ISE O KOLONU NULL OLARAK GETIRIR.

SELECT NULLIF(0,0)

SELECT HedefStokDuzeyi FROM Urunler
SELECT AVG(HedefStokDuzeyi) FROM Urunler

--HEDEF STOK DUZEYI 0 OLMAYAN URUNLERIN ORTALAMASI NEDIR?
--ASAGIDAKI IKI SORGU DA AYNI CIKTIYI DONDURUR
SELECT AVG(HedefStokDuzeyi) FROM Urunler WHERE HedefStokDuzeyi<>0
SELECT AVG(NULLIF(HedefStokDuzeyi,0)) FROM Urunler 
