--T-SQL DDL Giriş
USE Northwind
--DDL = DATA DEFINITION LANGUAGE
--TSQL'DE VERITABANI NESNELERI YARATMAYA VE BU YARATILAN NESNELER UZERINDE DEGISIKLIKLER YAPMAMIZI VEYA SILMEMIZI SAGLAR.

--CREATE, ALTER, DROP

