--T-SQL DDL Create Komutu İle Database Oluşturma

--###CREATE###

CREATE DATABASE ORNEKVERITABANI
--YUKARIDAKI GIBI BIR KULLANIMDA SYSTEM DATABASE ALTINDA BULUNAN 'MODEL' ORNEK ALINARAK BIR DATABASE OLUSTURULUR.

CREATE DATABASE ORNEKVERITABANI
ON
(
NAME='HY',
FILENAME='D:\HY.MDF',
SIZE=5,
FILEGROWTH=3
)

--NAME --> VERITABANININ FIZIKSEL ISMI.
--FILENAME --> VERITABANININ DIZINI.
--SIZE --> (MB CINSINDEN) VERITABANI BASLANGIC BOYUTU.
--FILEGROWTH --> (MB CINSINDEN) VERITABANI BOYUTU, BAŞLANGIÇ BOYUTUNU GEÇTİĞİ DURUMDA, BOYUTUN NE KADAR ARTMMASI GEREKTIGINI BELIRTIR.