--T-SQL DDL Create Komutu İle Database Log Dosyası Oluşturma

--DATABASE DOSYA UZANTISI .MDF İKEN, LOG DOSYA UZANTISI .LDF OLMAKTADIR!

CREATE DATABASE ORNEKVERITABANI
ON
(
NAME='HY',
FILENAME='D:\HY.MDF',
SIZE=5,
FILEGROWTH=3
)
LOG
ON
(
NAME='HY_LOG',
FILENAME='D:\HY.LDF',
SIZE=5,
FILEGROWTH=3
)