--T-SQL DDL Create Komutu İle Tablonun Kolonuna Primary Key ve Identity Özellikleri Verme

USE ORNEKVERITABANI

CREATE TABLE ORNEKVERITABANI3
(
ID INT PRIMARY KEY IDENTITY(1,1), --PRIMARY KEY OLACAK VE IDENTITY 1'DEN BASLAYIP 1'ER 1'ER ARTACAK ANLAMINA GELIR,
[KOLON 2] NVARCHAR(MAX),
[KOLON 3] MONEY
)