--T-SQL DDL Drop Komutu
USE ORNEKVERITABANI
--###DROP###

--CREATE ILE OLUSTURULAN NESNELERI SILMEMIZI SAGLAR.

--PROTOTIP
--DROP [NESNE_TIPI] [NESNE_ADI]

DROP TABLE ORNEKTABLOYENI
DROP DATABASE ORNEKVERITABANI