--T-SQL Constraintler Giriş

--CONSTRAINT (KISITLAYICILAR)
--CONSTRAINTLER SAYESINDE TABLO UZERINDE ISTEDIGIMIZ SARTLAR VE DURUMLARA GORE KISITLAMALAR YAPABILIRIZ.

--1. DEFAULT CONSTRAINT
--2. CHECK CONSTRAINT
--3. PRIMARY KEY CONSTRAINT
--4. UNIQUE CONSTRAINT
--5. FOREIGN KEY CONSTRAINT