--T-SQL Default Constraint

--DEFAULT CONSTRAINT SAYESINDE KOLONA BIR DEGER GIRILMEDIGI TAKTIRDE VARSAYILAN OLARAK NE GIRILMESI GEREKTIGINI BELIRTEBILIRIZ.
--GENEL YAPISI

--ADD CONSTRAINT [CONSTRAINT_ADI] DEFAULT '[VARSAYILACAK_DEGER]' FOR [KOLON_ADI]

USE Northwind

CREATE TABLE ORNEKTABLO
(
	ID INT PRIMARY KEY IDENTITY (1,1),
	KOLON1 NVARCHAR(MAX),
	KOLON2 INT
)

ALTER TABLE ORNEKTABLO
ADD CONSTRAINT KOLON1CONSTRAINT DEFAULT 'BOŞ' FOR KOLON1

ALTER TABLE ORNEKTABLO
ADD CONSTRAINT KOLON2CONSTRAINT DEFAULT -1 FOR KOLON2

INSERT ORNEKTABLO(KOLON2) VALUES(0)
INSERT ORNEKTABLO(KOLON1) VALUES('ORNEK DEGER')

SELECT * FROM ORNEKTABLO