--T-SQL Check Constraint
USE Northwind
--###CHECK CONSTRAINT###
--BIR KOLONA GIRILECEK VERININ BELIRLI BIR SARTA UYMASINI SAGLAR

--GENEL YAPISI 
--ADD CONSTRAINT [CONSTRAINT ADI] CHECK (ŞART)

ALTER TABLE ORNEKTABLO
ADD CONSTRAINT KOLON2KONTROL CHECK ((KOLON2 * 5) % 2 = 0)

--DIKKAT!!
--EGER CHECK CONSTRAINT OLUSTURULMADAN ONCE, TABLODA, OLUŞTURULACAK OLAN CONSTRAINTE KARŞI OLAN DEĞERLER VAR ISE, CONSTRAINT OLUŞMAYACAKTIR.!!!!
--ANCAK ONCEKI KAYITLARI GOZARDI EDIP YINE DE CONSTRAINTI OLUSTURMAK ISTIYORSAK ''WITH NOCHECK'' KOMUTU KULLANILABILIR.

