--T-SQL Check Constraint With Nocheck Komutu
USE Northwind

--WITH NOCHECK KOMUTU
--SU ANA KADAR OLAN KAYITLARI GORMEZDEN GELIP, YENI EKLENECEK KAYITLAR ICIN CONSTRAINT EKLER.
ALTER TABLE ORNEKTABLO
WITH NOCHECK ADD CONSTRAINT KOLON2KONTROL CHECK ((KOLON2 * 5) % 2 = 0)