--T-SQL Primary Key Constraint
USE Northwind

--###PRIMARY KEY CONSTRAINT###
--PKEY CONSTRAINT ILE; O KOLONA EKLENEN PRIMARY KEY ILE, BASKA TABLOLARDA FOREIGN KEY OLUSTURARAK ILISKI KURMAMIZ MUMKUN OLUR.
--BUNUN YANINDA O KOLONUN TASIDIGI VERININ TEKIL OLACAGI DA GARANTI EDILMIS OLUR. PRIMARY KEY CONSTRAINT ILE AYRICA ''CLUSTERED INDEX'' DE OLUSTURULMUS OLUR.

--GENEL YAPISI 
--ADD CONSTRAINT [CONSTRAINT_ADI] PRIMARY KEY (KOLON_ADI)

--DIKKAT !!!
--PRIMARY KEY CONSTRAINT UYGULANACAK OLAN KOLONUN BULUNDUGU TABLODA, PRIMARY KEY OLMAMALIDIR.
--PRIMARY KEY CONSTRAINT KULLANILAN KOLON, PRIMARY KEY OZELLIGINE SAHIP OLMAMALIDIR.

ALTER TABLE ORNEKTABLO
ADD CONSTRAINT PrimaryID PRIMARY KEY (ID)