--T-SQL Foreign Key Constraint Set Null Komutu
USE Northwind

--##SET NULL 
--ANA TABLODAKI KAYIT SILINDIGINDE VEYA GUNCELLENDIGINDE, ILISKILI KOLONDAKI KARSILIGINI ''NULL'' OLARAK GUNCELLER.

ALTER TABLE OGRENCILER
ADD CONSTRAINT FK_OGRENCI_DERS FOREIGN KEY (DERSID) REFERENCES DERSLER(DERSID)
ON DELETE SET NULL
ON UPDATE SET NULL