--T-SQL Foreign Key Constraint Set Default Komutu
USE Northwind

--###SET DEFAULT
--ANA TABLODAKI BIR KAYIT SILINDIGINE VEYA GUNCELLENDIGINDE, ILISKILI KOLONDAKI KARSILIGINA O KOLONUN DEFAULT DEGERI BASILIR. BU DEFAULT DEGER DEDIGIMIZ, DEFAULT TIPINDEN BIR CONSTRAINTTIR. BUNU KENDIMIZ OLUSTURABILIRIZ.

ALTER TABLE OGRENCILER
ADD CONSTRAINT DEFAULTOGRENCILER DEFAULT -1 FOR DERSID

ALTER TABLE OGRENCILER
ADD CONSTRAINT FK_OGRENCI_DERS FOREIGN KEY (DERSID) REFERENCES DERSLER(DERSID)
ON DELETE SET DEFAULT
ON UPDATE SET DEFAULT

--FOREIGN KEY TANIMLARKEN BU AYARLAR VERILMEDIGI TAKTIRDE ''NO ACTION'' OZELLIGI GECERLIDIR.
