--T-SQL Değişken Tanımlama
USE Northwind

--DECLARE KEYWORDU ILE TANIMLANIRLAR.

--PROTOTIP
--DECLARE @DEGISKEN_ADI DEGISKEN_TIPI

DECLARE @X INT
DECLARE @Y NVARCHAR
DECLARE @Z MONEY

DECLARE @X INT, @Y NVARCHAR, @Z BIT

DECLARE @YAS INT = -3
