--T-SQL Sorgu Sonucu Gelen Verileri Değişkenle Elde Etme
USE Northwind

SELECT * FROM Personeller

--!!!!
--1. SORGU SONUCU GELEN SATIR SAYISI BIR ADET OLMALIDIR.
--2. KOLONDAKI VERILERIN TIPLERI NE ISE, O VERILERI TEMSIL EDECEK DEGISKENLERIN VERI TIPLERI DE AYNISI OLMALIDIR.

SELECT Adi, SoyAdi FROM Personeller WHERE PersonelID = 1
DECLARE @AD NVARCHAR(MAX), @SOYAD NVARCHAR(MAX)
SELECT @AD=Adi, @SOYAD=SoyAdi FROM Personeller WHERE PersonelID = 1
SELECT @AD,@SOYAD