--T-SQL Batch Kavramı - Go Komutu
USE Northwind

--GO KOMUTU ISLEMLERI ADIM ADIM YAPTIRMAK ISTENDIGINDE KULLANILIR.
--AŞAĞIDAKI KOMUT HATA VERECEKTIR.
CREATE DATABASE ORNEKDATABASE
USE ORNEKDATABASE
CREATE TABLE ORNEKTABLE
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	AD NVARCHAR(MAX),
	SOYAD NVARCHAR(MAX)
)


--ANCAK ASAGIDAKI KOMUT SETI CALISACAKTIR.
CREATE DATABASE ORNEKDATABASE
GO
USE ORNEKDATABASE
GO
CREATE TABLE ORNEKTABLE
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	AD NVARCHAR(MAX),
	SOYAD NVARCHAR(MAX)
)

