--T-SQL If- Else If - Else Yapısı
USE Northwind

DECLARE @AD NVARCHAR(MAX) = 'HASAN'
DECLARE @YAS INT = 26

IF @AD = 'HASAN'
PRINT 'EVET, HASAN'
ELSE IF @YAS > 20
PRINT '20 YASINDAN BUYUK'
ELSE 
PRINT 'HATA!'