--T-SQL Exists Fonksiyonu
USE Northwind

--BIR TABLONUN DOLU VE YA BOS OLMASI HAKKINDA BOOLEAN (BIT) DEGER DONDURUR.

SELECT * FROM Personeller

IF EXISTS(SELECT * FROM Personeller)
PRINT 'DOLU'
ELSE 
PRINT 'BOŞ'