--T-SQL Geçici Tablolar
--###TEMPORARY TABLES-TEMP TABLES###

--GENELLIKLE BIR SQL SERVER UZERINDE FARKLI LOKASYONLARDA BIRDEN FAZLA KISININ CALISTIGI DURUMLARDA YA DA VERILERIN TEST AMACLI GECICI OLARAK BIR YERDE TUTULMASINI, ISLENMESINI GEREKTIREN DURUMLARDA KULLANILIR.

--BILINEN TABLO YAPISININ AYNISINI SAGLARLAR. TEK FARKLARI FIZIKSEL OLARAK OLUSMAZLAR. GECICI OLARAK RAM'DE TUTULURLAR.

--SELECT, INSERT, UPDATE VE DELETE ISLEMLERI YAPILABILIR. ILISKI KURULABILIR.

--SUNUCU KAPATILDIGINDA YA DA OTURUM SAHIBI OTURUMU KAPATTIGINDA SILINIRLER.

