--T-SQL Geçici Tablolar - Bir Tabloyu # İfadesi İle Belleğe Geçici Olarak Kopyalama
USE Northwind


--BIR TABLOYU # IFADESI ILE BELLEGE GECICI OLARAK KOPYALAMA
SELECT * INTO #GECICIPERSONELLER FROM Personeller
SELECT * FROM #GECICIPERSONELLER

INSERT #GECICIPERSONELLER(Adi,SoyAdi) VALUES('HASAN','YURDAKUL')
DELETE FROM #GECICIPERSONELLER WHERE PersonelID = 3
UPDATE #GECICIPERSONELLER SET Adi = 'HASAN', SoyAdi = 'YURDAKUL' WHERE PersonelID = 5

--GECICI TABLO UZERINDE HER TURLU ISLEMI YAPABILIRIZ.
--# ILE OLUSTURULAN TABLO, O AN SQL SERVERDA OTURUM ACMIS KISININ SUNUCU BELLEGINDE OLUSUR.
--SADECE OTURUM ACAN SAHIS KULLANABILIR.
--EGER OTURUM ACAN SAHIS SQL SERVERDAN DISCONNECT OLURSA BU TABLO BELLEKTEN SILINIR.