--T-SQL Geçici Tablolar - Bir Tabloyu ## İfadesi İle Belleğe Geçici Olarak Kopyalama
USE Northwind

SELECT * INTO ##GECICIPERSONELLER2 FROM Personeller

SELECT * FROM ##GECICIPERSONELLER2
INSERT ##GECICIPERSONELLER2(Adi,SoyAdi) VALUES('HASAN','YURDAKUL')
DELETE FROM ##GECICIPERSONELLER2 WHERE PersonelID = 3
UPDATE ##GECICIPERSONELLER2 SET Adi = 'HASAN', SoyAdi = 'YURDAKUL' WHERE PersonelID = 5

--## ILE OLUSTURULAN TABLO, O AN SQL SERVERDA OTURUM ACMIS KISININ SUNUCU BELLEGINDE OLUSUR.
--BU TABLOYU OTURUM ACAN SAHIS VE ONUN SQL SERVERINDA DISARDAN ULASAN 3. SAHISLAR KULLANABILIR.
--EGER OTURUM ACAN SAHIS SQL SERVERDAN DISCONNECT OLURSA BU TABLO BELLEKTEN SILINIR.
--DIGER TUM OZELLIKLERI # ILE OLUSTURULAN TABLO ILE AYNIDIR.

