--T-SQL Uniqueidentifier Veri Tip ve NEWID FonksiyonuUSE Northwind

--INT, VARCHAR VS. GIBI BIR VERI TIPIDIR.
--ALDIGI DEGER, RAKAMLAR VE HARFLERDEN OLUSAN COK BUYUK BIR SAYIDIR.
--BUNDAN DOLAYI BU KOLONA AYNI DEGERIN BIRDEN FAZLA KEZ GELMESI IHTIMALI NEREDEYSE IMKANSIZDIR.
--BU SAYEDE TEKIL BIR VERI OLUSTURMAK ICIN KULLANILIR.

CREATE TABLE ORNEKTABLO
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	KOLON1 NVARCHAR(MAX),
	KOLON2 NVARCHAR(MAX),
	KOLON3 UNIQUEIDENTIFIER
)

--NEWID
SELECT NEWID()
INSERT ORNEKTABLO VALUES('X','Y',NEWID())

