--T-SQL View - With Encryption Komutu

--###############################
--WITH ENCRYPTION KOMUTU
--EGER YAZDIGIMIZ VIEWLARIN KAYNAK KODLARINI, OBJECT EXPLORER PENCERESINDE BULUNAN ''VIEWS'' KATEGORISINE SAG TIKLAYARAK, DESIGN MODDA ACIP GORUNTULENMESINI ISTEMIYORSAK, ''WITH ENCRYPTION'' KOMUTU ILE VIEW'I OLUSTURMALIYIZ.

--!!DIKKAT!!
--''WITH ENCRYPTION'' ISLEMINDEN SONRA VIEW'I OLUSTURULAN KISI DE DAHIL KIMSE KOMUTLARI GOREMEZ. GERI DONUS YOKTUR. ANCAK VIEW'I OLUSTURAN KISININ KOMUTLARIN YEDEGINI BULUNDURMASI GEREKLIDIR. YA DA ''WITH ENCRYPTION'' OLMADAN VIEW YAPISINI ''ALTER'' KOMUTU ILE BASTAN YAZMALIYIZ.
--''WITH ENCRYPTION'' KOMUTU ''AS'' KOMUTUNDAN ONCE YAZILMALIDIR.

CREATE VIEW ORNEKPERSONELVIEW
WITH ENCRYPTION
AS
SELECT Adi,SoyAdi,Unvan FROM Personeller

--BU ISLEMI YAPTIKTAN SONRA BU VIEW'IN DESIGN MODU KAPATILMISTIR.