--T-SQL View - With Schemabinding Komutu

--##############################
--WITH SCHEMABINDING KOMUTU
--EGER VIEW'IN KULLANDIGI ESAS FIZIKSEL TABLOLARIN KOLON ISIMLERI BIR SEKILDE DEGISTIRILIR, KOLONLARI SILINIR YA DA TABLO YAPISI BIR SEKILDE DEGISIKLIGE UGRAR ISE VIEW'IN CALISMASI ARTIK MUMKUN OLMAYACAKTIR.
--VIEW'IN KULLANDIGI TABLOLAR VE KOLONLARI BU TARZ ISLEMLERIN YAPILABILMESI IHTIMALINE KARSI KORUMA ALTINA ALINABILIR.
--BU KORUMA, WITH ''WITH SCHEMABINDING'' KOMUTU ILE SAGLANABILMEKTEDIR.
--''WITH SCHEMABINDING'' ILE VIEW, CREATE VEYA ALTER EDILIRKEN, VIEW'IN KULLANDIGI TABLO, SCHEMA ADIYLA BERABER VERILMELIDIR. ORNEGIN, dbo(DATABASE OWNER) BIR SEMA ADIDIR. SEMALAR C#'TAKI NAMESPACE'LER GIBI DUSUNULEBILIR.
--''WITH SCHEMABINDING'' KOMUTU DA ''AS'' KELIMESINDEN ONCE YAZILMALIDIR.

CREATE TABLE ORNEKTABLO 
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	KOLON1 NVARCHAR(MAX)
)

CREATE VIEW ORNEKVIEW
WITH SCHEMABINDING
AS
SELECT ID,KOLON1 FROM dbo.ORNEKTABLO


--WITH SCHEMABINDING ILE OLUSTURULDUGUNDAN DOLAYI, KOLON1'IN VERI TIPINI INT'E CEVIREMEYECEGIZ.
ALTER TABLE ORNEKTABLO
ALTER COLUMN KOLON1 INT