--T-SQL Fonksiyonlar Giriş

--FUNCTIONS - SCALAR FUNCTION - INLINE FUNCTION

--T-SQL'DE IKI TIP FONKSIYON VARDIR.
--SCALAR FUNCTION = GERIYE ISTEDIGIMIZ BIR TIPTE DEGER GONDEREN FONKSIYON
--INLINE FUNCTION = GERIYE TABLO GONDEREN FONKSIYON

--BU HER IKI FONKSIYON DA FIZIKSEL OLARAK VERITABANINDA OLUSTURULMAKTADIR.
--CREATE KOMUTU ILE OLUSTURULMAKTADIRLAR.
--UZERINDE CALISILAN DATABASE'IN ''PROGRAMMABILITY-->FUNCTIONS'' DIZININDE ULASILABILIRLER.