--T-SQL Scalar Functions - Tanımlama

--##############################
--FONKSIYON TANIMLAMA
--SCALAR FONKSIYONLARA TANIMLANDIKTAN SONRA, ''PROGRAMMABILITY --> FUNCTIONS --> SCALAR-VALUED FUNCTIONS'' DIZININDEN ERISEBILIRIZ.

CREATE FUNCTION TOPLA(@SAYI1 INT, @SAYI2 INT)
RETURNS INT
AS
BEGIN
	RETURN @SAYI1 + @SAYI2
END

