--T-SQL Scalar Functions - Kullanım

--################################
--FONKSIYON KULLANIMI
--FONKSIYON KULLANILIRKEN SEMASI ILE BERABER CAGIRILMALIDIR.
SELECT dbo.TOPLA(2,5)
PRINT dbo.TOPLA(10,25)

--## ORNEK ##
--''NORTHWIND'' VERITABANINDA, HERHANGI BIR URUNUN %18 KDV DAHIL OLMAK UZERE TOPLAM MALIYETINI GETIREN BIR FONKSIYON YAZINIZ.
USE Northwind
GO
CREATE FUNCTION MALIYET(@BIRIMFIYAT INT, @STOKMIKTARI INT)
RETURNS NVARCHAR(MAX)
AS
BEGIN
	DECLARE @MALIYET NVARCHAR(MAX)
	SET @MALIYET = CAST((@BIRIMFIYAT * @STOKMIKTARI * 1.18) AS NVARCHAR(MAX))
	RETURN @MALIYET
END

SELECT dbo.MALIYET(10,20)